name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
#    strategy:
#      matrix:
#        os: [ubuntu-24.04]
    uses: ./.github/workflows/ci-base.yml
    with:
      os: ubuntu-latest
