name: CI Base

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
#    runs-on: ${{ inputs.os }}
    runs-on: ubuntu-24.04

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v4

    - name: Expose GitHub Action Variables
      uses: crazy-max/ghaction-github-runtime@v3

    - name: Install Maelstrom Broker
      uses: jaxxstorm/action-install-gh-release@master
      with:
        repo: maelstrom-software/maelstrom
        asset-name: maelstrom-broker

    - name: Disable Apparmor Container Restrictions for Maelstrom
      run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

    - name: Start Maelstrom Broker
      run: |
        TEMPFILE=$(mktemp maelstrom-broker-stderr.XXXXXX)
        maelstrom-broker 2> >(tee "$TEMPFILE" >&2) &
        PID=$!
        PORT=$( \
          tail -f "$TEMPFILE" \
          | awk '/\<addr: / { print $0; exit}' \
          | sed -Ee 's/^.*\baddr: [^,]*:([0-9]+),.*$/\1/' \
        )
        echo "MAELSTROM_BROKER_PID=$PID" >> "$GITHUB_ENV"
        echo "CARGO_MAELSTROM_BROKER=localhost:$PORT" >> "$GITHUB_ENV"
        echo "CARGO_MAELSTROM_ARTIFACT_TRANSFER_STRATEGY=github" >> "$GITHUB_ENV"
      env:
        MAELSTROM_BROKER_ARTIFACT_TRANSFER_STRATEGY: github
        ACTIONS_RUNTIME_TOKEN: ${{ env.ACTIONS_RUNTIME_TOKEN }}
        ACTIONS_RESULTS_URL: ${{ env.ACTIONS_RESULTS_URL }}

    - name: Install cargo-maelstrom
      uses: jaxxstorm/action-install-gh-release@master
      with:
        repo: maelstrom-software/maelstrom
        asset-name: cargo-maelstrom

    - name: Run cargo-maelstrom
      run: cargo maelstrom
      working-directory: cargo-workspace

    - name: Kill Maelstrom Broker
      run: kill -15 $MAELSTROM_BROKER_PID

  maelstrom-worker:
    strategy:
      matrix:
        worker-number: [1, 2, 3, 4]

    name: Maelstrom Worker ${{ matrix.worker-number }}
    runs-on: ubuntu-24.04

#    runs-on: ${{ inputs.os }}

    steps:
    - name: Expose GitHub Action Variables
      uses: crazy-max/ghaction-github-runtime@v3

    - name: Install Maelstrom Worker
      uses: jaxxstorm/action-install-gh-release@master
      with:
        repo: maelstrom-software/maelstrom
        asset-name: maelstrom-worker

    - name: Disable Apparmor Container Restrictions for Maelstrom
      run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

    - name: Run Maelstrom Worker
      run: maelstrom-worker || true
      env:
        ACTIONS_RUNTIME_TOKEN: ${{ env.ACTIONS_RUNTIME_TOKEN }}
        ACTIONS_RESULTS_URL: ${{ env.ACTIONS_RESULTS_URL }}
        MAELSTROM_WORKER_ARTIFACT_TRANSFER_STRATEGY: github
        MAELSTROM_WORKER_BROKER_CONNECTION: github
        MAELSTROM_WORKER_BROKER: 0.0.0.0:0
