name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install the lastest cargo-maelstrom
      uses: jaxxstorm/action-install-gh-release@v1.14.0
      with:
        repo: maelstrom-software/maelstrom
        asset-name: cargo-maelstrom
    - name: Disable apparmor container restrictions
      run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
    - name: Run tests
      run: cd cargo-workspace && cargo maelstrom 
